apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-bank-app
  labels:
    app: web-bank-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-bank-app
  template:
    metadata:
      labels:
        app: web-bank-app
    spec:
      containers:
        - name: web-bank-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
