apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: web-bank-app-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "web-bank-app-db-password"
        objectType: "secretsmanager"
