apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-bank-app-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::536697262404:role/web-bank-app-irsa
